//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitSetting {
	using System;



	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Localizable {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Localizable() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localizable", typeof(Localizable).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Run HoneyPot Inspector.
		/// </summary>
		internal static string AppHPInspector {
			get {
				return ResourceManager.GetString("AppHPInspector", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Visit Discord.
		/// </summary>
		internal static string ButtonDiscord {
			get {
				return ResourceManager.GetString("ButtonDiscord", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Visit Patreon.
		/// </summary>
		internal static string ButtonPatreon {
			get {
				return ResourceManager.GetString("ButtonPatreon", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		internal static string ButtonUpdate {
			get {
				return ResourceManager.GetString("ButtonUpdate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This game is intended for adult audiences, no person under the age of 18 (or equivalent according to local law) are supposed to play or be in possession of this game.
		///
		///This game contains content of a sexual nature, and some of the actions depicted within may be illegal to replicate in real life. Aka, it&apos;s all fun and games in the game, let&apos;s keep it that way shall we? (~.~)v.
		/// </summary>
		internal static string Disclaimer {
			get {
				return ResourceManager.GetString("Disclaimer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unknown distribution.
		/// </summary>
		internal static string Distribution {
			get {
				return ResourceManager.GetString("Distribution", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Female Card Folder.
		/// </summary>
		internal static string FolderFemaleCard {
			get {
				return ResourceManager.GetString("FolderFemaleCard", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Houses Folder.
		/// </summary>
		internal static string FolderHouses {
			get {
				return ResourceManager.GetString("FolderHouses", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Install Folder.
		/// </summary>
		internal static string FolderInstall {
			get {
				return ResourceManager.GetString("FolderInstall", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Male Card Folder.
		/// </summary>
		internal static string FolderMaleCard {
			get {
				return ResourceManager.GetString("FolderMaleCard", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Scenes Folder.
		/// </summary>
		internal static string FolderScenes {
			get {
				return ResourceManager.GetString("FolderScenes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Screenshots Folder.
		/// </summary>
		internal static string FolderScreenshots {
			get {
				return ResourceManager.GetString("FolderScreenshots", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to UserData Folder.
		/// </summary>
		internal static string FolderUserData {
			get {
				return ResourceManager.GetString("FolderUserData", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Game Manual.
		/// </summary>
		internal static string ManualGame {
			get {
				return ResourceManager.GetString("ManualGame", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Studio Manual.
		/// </summary>
		internal static string ManualStudio {
			get {
				return ResourceManager.GetString("ManualStudio", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to VR Manual.
		/// </summary>
		internal static string ManualVR {
			get {
				return ResourceManager.GetString("ManualVR", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PrimaryDisplay.
		/// </summary>
		internal static string PrimaryDisplay {
			get {
				return ResourceManager.GetString("PrimaryDisplay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Normal.
		/// </summary>
		internal static string QualityNormal {
			get {
				return ResourceManager.GetString("QualityNormal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Performance.
		/// </summary>
		internal static string QualityPerformance {
			get {
				return ResourceManager.GetString("QualityPerformance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Quality.
		/// </summary>
		internal static string QualityQuality {
			get {
				return ResourceManager.GetString("QualityQuality", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Height.
		/// </summary>
		internal static string ResHeight {
			get {
				return ResourceManager.GetString("ResHeight", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Width.
		/// </summary>
		internal static string ResWidth {
			get {
				return ResourceManager.GetString("ResWidth", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Start Game.
		/// </summary>
		internal static string StartGame {
			get {
				return ResourceManager.GetString("StartGame", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Start Studio.
		/// </summary>
		internal static string StartStudio {
			get {
				return ResourceManager.GetString("StartStudio", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Start VR.
		/// </summary>
		internal static string StartVR {
			get {
				return ResourceManager.GetString("StartVR", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SubDisplay.
		/// </summary>
		internal static string SubDisplay {
			get {
				return ResourceManager.GetString("SubDisplay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate AI Graphics.
		/// </summary>
		internal static string ToggleAiGraphics {
			get {
				return ResourceManager.GetString("ToggleAiGraphics", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate Bonemod.
		/// </summary>
		internal static string ToggleBonemod {
			get {
				return ResourceManager.GetString("ToggleBonemod", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate Console.
		/// </summary>
		internal static string ToggleConsole {
			get {
				return ResourceManager.GetString("ToggleConsole", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate DHH.
		/// </summary>
		internal static string ToggleDhh {
			get {
				return ResourceManager.GetString("ToggleDhh", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Play game in fullscreen.
		/// </summary>
		internal static string ToggleFullscreen {
			get {
				return ResourceManager.GetString("ToggleFullscreen", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate HoneyPot.
		/// </summary>
		internal static string ToggleHoneyPot {
			get {
				return ResourceManager.GetString("ToggleHoneyPot", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate RimRemover.
		/// </summary>
		internal static string ToggleRimRemover {
			get {
				return ResourceManager.GetString("ToggleRimRemover", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate Stiletto.
		/// </summary>
		internal static string ToggleStiletto {
			get {
				return ResourceManager.GetString("ToggleStiletto", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Activate VRMod.
		/// </summary>
		internal static string ToggleVRMod {
			get {
				return ResourceManager.GetString("ToggleVRMod", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string TranslatedByCredit {
			get {
				return ResourceManager.GetString("TranslatedByCredit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AI Shoujo Launcher.
		/// </summary>
		internal static string WindowTitle {
			get {
				return ResourceManager.GetString("WindowTitle", resourceCulture);
			}
		}
	}
}