//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitSetting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitSetting.Localizable", typeof(Localizable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Discord.
        /// </summary>
        public static string ButtonDiscord {
            get {
                return ResourceManager.GetString("ButtonDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Patreon.
        /// </summary>
        public static string ButtonPatreon {
            get {
                return ResourceManager.GetString("ButtonPatreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is intended for adult audiences, no person under the age of 18 (or equivalent according to local law) are supposed to play or be in possession of this game.
        ///
        ///This game contains content of a sexual nature, and some of the actions depicted within may be illegal to replicate in real life. Aka, it&apos;s all fun and games in the game, let&apos;s keep it that way shall we? (~.~)v.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown distribution.
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Card Folder.
        /// </summary>
        public static string FolderFemaleCard {
            get {
                return ResourceManager.GetString("FolderFemaleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses Folder.
        /// </summary>
        public static string FolderHouses {
            get {
                return ResourceManager.GetString("FolderHouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Folder.
        /// </summary>
        public static string FolderInstall {
            get {
                return ResourceManager.GetString("FolderInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Card Folder.
        /// </summary>
        public static string FolderMaleCard {
            get {
                return ResourceManager.GetString("FolderMaleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenes Folder.
        /// </summary>
        public static string FolderScenes {
            get {
                return ResourceManager.GetString("FolderScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots Folder.
        /// </summary>
        public static string FolderScreenshots {
            get {
                return ResourceManager.GetString("FolderScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserData Folder.
        /// </summary>
        public static string FolderUserData {
            get {
                return ResourceManager.GetString("FolderUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Manual.
        /// </summary>
        public static string ManualGame {
            get {
                return ResourceManager.GetString("ManualGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Manual.
        /// </summary>
        public static string ManualStudio {
            get {
                return ResourceManager.GetString("ManualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryDisplay.
        /// </summary>
        public static string PrimaryDisplay {
            get {
                return ResourceManager.GetString("PrimaryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string QualityNormal {
            get {
                return ResourceManager.GetString("QualityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string QualityPerformance {
            get {
                return ResourceManager.GetString("QualityPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string QualityQuality {
            get {
                return ResourceManager.GetString("QualityQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ResHeight {
            get {
                return ResourceManager.GetString("ResHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ResWidth {
            get {
                return ResourceManager.GetString("ResWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Studio.
        /// </summary>
        public static string StartStudio {
            get {
                return ResourceManager.GetString("StartStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubDisplay.
        /// </summary>
        public static string SubDisplay {
            get {
                return ResourceManager.GetString("SubDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate AI Graphics.
        /// </summary>
        public static string ToggleAiGraphics {
            get {
                return ResourceManager.GetString("ToggleAiGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Console.
        /// </summary>
        public static string ToggleConsole {
            get {
                return ResourceManager.GetString("ToggleConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate DHH.
        /// </summary>
        public static string ToggleDhh {
            get {
                return ResourceManager.GetString("ToggleDhh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play game in fullscreen.
        /// </summary>
        public static string ToggleFullscreen {
            get {
                return ResourceManager.GetString("ToggleFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TranslatedByCredit {
            get {
                return ResourceManager.GetString("TranslatedByCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Shoujo Launcher.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
