<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<Resource Include="images\Chara.png" />
		<Resource Include="images\icon.ico" />
		<Resource Include="images\Logo.png" />
		<Resource Include="images\Background.png" />
	</ItemGroup>

	<Import Project="..\SharedCode\SharedCode.projitems" Label="Shared" />
	<Import Project="..\SharedSettingsNew\SharedSettingsNew.projitems" Label="Shared" />
</Project>