<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<Resource Include="images\Chara.png" />
		<Resource Include="images\icon.ico" />
		<Resource Include="images\Logo.png" />
		<Resource Include="images\Background.png" />
		<Resource Include="images\LaunchBG\classicBTN.png" />
		<Resource Include="images\LaunchBG\neoBTN.png" />
		<Resource Include="images\LaunchBG\oculusBTN.png" />
		<Resource Include="images\LaunchBG\PsuedoButton.png" />
		<Resource Include="images\LaunchBG\viveBTN.png" />
	</ItemGroup>

	<Import Project="..\SharedCode\SharedCode.projitems" Label="Shared" />
	<Import Project="..\SharedSettingsOld\SharedSettingsOld.projitems" Label="Shared" />
</Project>