<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<Resource Include="images\Chara.png" />
		<Resource Include="images\icon.ico" />
		<Resource Include="images\Logo.png" />
		<Resource Include="images\Background.png" />
	</ItemGroup>

	<Import Project="..\Shared\Shared.projitems" Label="Shared" />
	<Import Project="..\SharedIllgames\SharedIllgames.projitems" Label="Shared" />
</Project>